name: Issues Workflow

# issues  -> Fire there is any change (open/edit/close) issue in git repo
on: issues

jobs:
  check_issues_updates:
    runs-on: ubuntu-latest
    steps:
      - name: Output event details
        run: echo "${{ toJSON(github.event) }}"
