name: Issues Workflow

# issues  -> When new issue is opened in github repo
on: issues

jobs:
  check_issues_updates:
    runs-on: ubuntu-latest
    steps:
      - name: Output event details
        run: echo "${{ toJSON(github.event) }}"
